# Generated by Django 5.0.1 on 2024-02-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product'),
        ('shop', '0002_products'),
    ]

    operations = [
    ]
